package com.larastudio.pdfku;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.pdf.PdfRenderer;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;
import androidx.core.content.FileProvider;

public class MainActivity extends Activity{
 LinearLayout content; TextView status; ImageView image; PdfRenderer renderer; ParcelFileDescriptor fd; int page=0; final int PDF=1,IMG=2,MERGE=3; ArrayList<Uri> recent=new ArrayList<>();
 int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
 TextView tx(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setPadding(dp(12),dp(8),dp(12),dp(8));return t;}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 public void onCreate(Bundle b){super.onCreate(b);home();}
 void shell(String h){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(16),dp(16),dp(10));r.setBackgroundColor(Color.rgb(15,23,42));TextView t=tx(h,28);t.setTypeface(null,1);r.addView(t);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);r.addView(sv,new LinearLayout.LayoutParams(-1,0,1));status=tx("PDF-ku • Semua urusan PDF, satu aplikasi.",13);r.addView(status);setContentView(r);}
 void add(String s,View.OnClickListener l){Button b=bt(s);content.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));b.setOnClickListener(l);}
 void home(){shell("PDF-ku");content.addView(tx("Baca • Buat • Kelola • Bagikan",16));add("📄  Buka PDF",v->pickPdf());add("🖼️  Gambar → PDF",v->pickImg());add("✍️  Teks → PDF",v->textPdf());add("🧰  PDF Tools",v->tools());add("🕘  File Terakhir",v->recent());}
 void pickPdf(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/pdf");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PDF);}
 void pickImg(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMG);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==PDF&&d.getData()!=null){Uri u=d.getData();recent.remove(u);recent.add(0,u);open(u);}else if(r==IMG)imagePdf(d);else if(r==MERGE)mergeSelected(d);}
 void open(Uri u){try{closePdf();fd=getContentResolver().openFileDescriptor(u,"r");renderer=new PdfRenderer(fd);page=0;viewer();}catch(Exception e){toast("Gagal membuka PDF");}}
 void viewer(){shell("PDF Viewer");image=new ImageView(this);image.setAdjustViewBounds(true);image.setBackgroundColor(Color.WHITE);content.addView(image,new LinearLayout.LayoutParams(-1,0,1));LinearLayout n=new LinearLayout(this);Button p=bt("‹ Sebelumnya"),q=bt("Berikutnya ›"),b=bt("Beranda");Button save=bt("Simpan");n.addView(p,new LinearLayout.LayoutParams(0,56,1));n.addView(q,new LinearLayout.LayoutParams(0,56,1));n.addView(save,new LinearLayout.LayoutParams(0,56,1));n.addView(b,new LinearLayout.LayoutParams(0,56,1));content.addView(n);p.setOnClickListener(v->{if(page>0){page--;render();}});q.setOnClickListener(v->{if(page<renderer.getPageCount()-1){page++;render();}});save.setOnClickListener(v->saveCurrentPage());b.setOnClickListener(v->home());render();}
 void render(){try{PdfRenderer.Page p=renderer.openPage(page);Bitmap b=Bitmap.createBitmap(p.getWidth()*2,p.getHeight()*2,Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);p.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);p.close();image.setImageBitmap(b);status.setText("Halaman "+(page+1)+" / "+renderer.getPageCount());}catch(Exception e){toast("Gagal menampilkan halaman");}}
 void textPdf(){EditText e=new EditText(this);e.setHint("Tulis isi PDF…");e.setMinLines(8);new AlertDialog.Builder(this).setTitle("Teks → PDF").setView(e).setNegativeButton("Batal",null).setPositiveButton("Buat", (d,w)->makeText(e.getText().toString())).show();}
 void makeText(String s){if(s.trim().isEmpty()){toast("Teks kosong");return;}try{File f=new File(getExternalFilesDir(null),"PDF-ku-"+System.currentTimeMillis()+".pdf");PdfDocument d=new PdfDocument();PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Paint x=new Paint(1);x.setColor(Color.BLACK);x.setTextSize(16);float y=60;for(String line:s.split("\\n",-1)){if(y>800){d.finishPage(p);p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,d.getPages().size()+1).create());y=60;}p.getCanvas().drawText(line,40,y,x);y+=24;}d.finishPage(p);FileOutputStream o=new FileOutputStream(f);d.writeTo(o);o.close();d.close();toast("PDF dibuat: "+f.getName());}catch(Exception e){toast("Gagal membuat PDF");}}
 void imagePdf(Intent d){try{ArrayList<Uri> a=new ArrayList<>();if(d.getClipData()!=null)for(int i=0;i<d.getClipData().getItemCount();i++)a.add(d.getClipData().getItemAt(i).getUri());else if(d.getData()!=null)a.add(d.getData());File f=new File(getExternalFilesDir(null),"PDF-ku-gambar-"+System.currentTimeMillis()+".pdf");PdfDocument p=new PdfDocument();int n=1;for(Uri u:a){Bitmap b=BitmapFactory.decodeStream(getContentResolver().openInputStream(u));if(b==null)continue;float s=Math.min(535f/b.getWidth(),762f/b.getHeight());int w=(int)(b.getWidth()*s),h=(int)(b.getHeight()*s);PdfDocument.Page z=p.startPage(new PdfDocument.PageInfo.Builder(595,842,n++).create());z.getCanvas().drawBitmap(b,null,new RectF((595-w)/2f,(842-h)/2f,(595+w)/2f,(842+h)/2f),new Paint(1));p.finishPage(z);b.recycle();}FileOutputStream o=new FileOutputStream(f);p.writeTo(o);o.close();p.close();toast("PDF gambar dibuat");}catch(Exception e){toast("Gagal membuat PDF gambar");}}
 void tools(){shell("PDF Tools");add("🔗  Gabung PDF",v->pickMerge());add("✂️  Split PDF",v->toast("Buka PDF lalu tekan Simpan untuk menyimpan halaman aktif"));add("ℹ️  Tentang PDF-ku",v->new AlertDialog.Builder(this).setTitle("PDF-ku 1.0").setMessage("Toolkit PDF offline-first dari Lara Studio.").setPositiveButton("OK",null).show());add("⌂  Kembali",v->home());}
 void recent(){shell("File Terakhir");if(recent.isEmpty())content.addView(tx("Belum ada PDF yang dibuka.",16));for(Uri u:recent){Button b=bt("📄 "+u.getLastPathSegment());content.addView(b);b.setOnClickListener(v->open(u));}add("⌂  Kembali",v->home());}
 void pickMerge(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/pdf");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,MERGE);}
 void mergeSelected(Intent d){try{ArrayList<Uri> a=new ArrayList<>();if(d.getClipData()!=null)for(int i=0;i<d.getClipData().getItemCount();i++)a.add(d.getClipData().getItemAt(i).getUri());else if(d.getData()!=null)a.add(d.getData());if(a.size()<2){toast("Pilih minimal 2 PDF");return;}File f=new File(getExternalFilesDir(null),"PDF-ku-merge-"+System.currentTimeMillis()+".pdf");PdfDocument out=new PdfDocument();int no=1;for(Uri u:a){ParcelFileDescriptor pfd=getContentResolver().openFileDescriptor(u,"r");PdfRenderer rr=new PdfRenderer(pfd);for(int i=0;i<rr.getPageCount();i++){PdfRenderer.Page src=rr.openPage(i);int w=src.getWidth(),h=src.getHeight();PdfDocument.Page dst=out.startPage(new PdfDocument.PageInfo.Builder(w,h,no++).create());Bitmap bm=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);bm.eraseColor(Color.WHITE);src.render(bm,null,null,PdfRenderer.Page.RENDER_MODE_FOR_PRINT);dst.getCanvas().drawBitmap(bm,0,0,new Paint(1));out.finishPage(dst);bm.recycle();src.close();}rr.close();pfd.close();}FileOutputStream os=new FileOutputStream(f);out.writeTo(os);os.close();out.close();shareFile(f);}catch(Exception e){toast("Gagal menggabungkan PDF");}}
 void saveCurrentPage(){if(renderer==null)return;try{File f=new File(getExternalFilesDir(null),"PDF-ku-page-"+(page+1)+"-"+System.currentTimeMillis()+".pdf");PdfRenderer.Page src=renderer.openPage(page);PdfDocument out=new PdfDocument();PdfDocument.Page dst=out.startPage(new PdfDocument.PageInfo.Builder(src.getWidth(),src.getHeight(),1).create());Bitmap bm=Bitmap.createBitmap(src.getWidth(),src.getHeight(),Bitmap.Config.ARGB_8888);bm.eraseColor(Color.WHITE);src.render(bm,null,null,PdfRenderer.Page.RENDER_MODE_FOR_PRINT);dst.getCanvas().drawBitmap(bm,0,0,new Paint(1));out.finishPage(dst);src.close();bm.recycle();FileOutputStream os=new FileOutputStream(f);out.writeTo(os);os.close();out.close();shareFile(f);}catch(Exception e){toast("Gagal menyimpan halaman");}}
 void shareFile(File f){try{Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");Uri u=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Bagikan PDF"));}catch(Exception e){toast("PDF dibuat: "+f.getName());}}
 void closePdf(){try{if(renderer!=null)renderer.close();}catch(Exception e){}try{if(fd!=null)fd.close();}catch(Exception e){}renderer=null;fd=null;}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 protected void onDestroy(){closePdf();super.onDestroy();}
}
